# Generated by Django 5.2.3 on 2025-06-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
