# Generated by Django 5.2.3 on 2025-06-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
