# Generated by Django 5.2.3 on 2025-06-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_ordermodel_email_ordermodel_name_ordermodel_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='tel',
            field=models.CharField(max_length=10),
        ),
    ]
