# Generated by Django 5.2.3 on 2025-07-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_ordermodel_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='tel',
            field=models.CharField(max_length=9),
        ),
    ]
