# Generated by Django 5.2.3 on 2025-07-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_ordermodel_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
